### ISSUE TITLE
When will it be released?

### ISSUE THREAD

**Issue by wwWT000** [Icepenguins101/charms-bar-port#1]
WHEN WILL IT BE RELEASED?????

**Comment by Icepenguins101** [comment]
I have no idea yet.

**Comment by Ark2011-s** [comment]
> 我还不知道。

WHAT????????
Wouldn't you haven't developed it yet?
（i am a chinese and use translate tools)

**Comment by Aoi-hosizora** [comment]
@Ark2011-s Is the screenshot in README (https://github.com/Icepenguins101/charms-bar-port/blob/main/resource/preview.png) taken on Windows 8.1? or on Windows 10?

You said this repository is forked from CharmsBarRevived, but the forked repository just simulate Charms Bar, and is not the real one in 8.1. 😂

**Comment by Ark2011-s** [comment]
> @Ark2011-s自述文件 （https://github.com/Icepenguins101/charms-bar-port/blob/main/resource/preview.png） 中的屏幕截图是在 Windows 8.1 上拍摄的吗？还是在 Windows 10 上？
> 
> 你说这个仓库是从 CharmsBarRevived 分叉的，但分叉的仓库只是模拟 Charms Bar，并不是 8.1 中真正的仓库。😂

i think it is a windows 8.1 screenshot......

**Comment by Icepenguins101** [comment]
> @Ark2011-s Oh sorry, I mentioned a wrong user😂, I should @Icepenguins101.
> 
> By the way I notice that the USB tray icon in task bar is in Windows 10 style, but the speaker, network and battery icons are in Windows 8 style.

It's Windows 10, I largely transformed it into Windows 8.1 because I do not like its default UI.

**Comment by LazytownSpo666** [comment]
@Icepenguins101, the creator of CharmsBarPort is currently focusing on other personal things, and currently, he doesn't have a free time yet. so stop asking him whether or not the project will deliver its first release.

Also, asking for ETA is COMPLETELY useless. It will be done when it's done.

**Comment by arduinoturkbatu** [comment]
Windows 8.1 didn't have Cortana. This is 10

**Comment by 123MEMZ** [comment]
这是来自QQ邮箱的自动回复邮件。本人正在休假中，看见邮件会第一时间回复。

**Comment by CosmicEternityCD** [comment]
This looks AMAZING SO FAR! I am making a project called Project Midori where its a replica of Windows 8.1 in Windows 10. Can I use this when its ready?
(also omg another windows modder with a splatoon pfp)

**Comment by Icepenguins101** [comment]
@CosmicEternityCD the release date is still undetermined, and I’m more of a Mac type, but the pfp is because of 2018 manipulations

**Comment by LazytownSpo666** [comment]
Charms Bar Port will deliver its first release in a long-term.

**Comment by LazytownSpo666** [comment]
Okay seriously, when will this be released?

**Comment by Icepenguins101** [comment]
I hope sometime when my PC is fully fixed. I’ve been working on another project called Australis Theme Port for Firefox during this hiatus.

**Comment by Icepenguins101** [comment]
(Quick update)

This project is indefinitely delayed because there are PC repair holdovers. Please do not ask me the same thing again regarding the project as I have other things to do. The project is not going to be abandonware, nor do I care to even resume with the amount of months lost without any updates (7 months).

**Comment by LazytownSpo666** [comment]
Why are you reopening this issue?

**Comment by Icepenguins101** [comment]
It was so that I can notify that the project isn’t going to be completely abandoned despite the ongoing PC repairs. There’s still going to be minor fixes until the next big update comes when i get the computer back from the repair shop.Sent from my iPhoneOn Sep 20, 2024, at 11:10 PM, Lazytown Sportacus ***@***.***> wrote:﻿
Why are you reopening this issue?

**Comment by Icepenguins101** [comment]
Bumping this to announce that the machine has been fixed. Updates might resume somewhere around this month.

**Comment by LazytownSpo666** [comment]
> Bumping this to announce that the machine has been fixed. Updates might resume somewhere around this month.

It's June 2nd, 2025 (at the time), and it's still not released.

**Comment by Icepenguins101** [comment]
Pff, yeah, the reason is because the shop is asking for a $200 price range to get my computer back to me.
